"""modified constraints

Revision ID: 56c6019925c6
Revises: 
Create Date: 2022-07-10 18:25:48.807970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c6019925c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'imageUrl',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('recipe', 'notes',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_unique_constraint(None, 'recipe', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    op.alter_column('recipe', 'notes',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('recipe', 'imageUrl',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    # ### end Alembic commands ###
